/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/athlete.glb 
Author: restore50 (https://sketchfab.com/restore50)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shirtless-athlete-in-black-shorts-e6281bc9c81c4ce59fc53da74b8bcb8f
Title: Shirtless Athlete in Black Shorts
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { ThreeElements } from "@react-three/fiber";

export function Athlete(props: ThreeElements["group"]) {
  const { nodes, materials } = useGLTF('/models/athlete.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_5.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.material_0} />
    </group>
  )
}

useGLTF.preload('/models/athlete.glb')
